/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: 'hsl(var(--card))',
        'card-foreground': 'hsl(var(--card-foreground))',
        'card-border': 'hsl(var(--border))',
        surface: 'hsl(var(--card))',
        'surface-raised': 'hsl(var(--muted))',
        primary: 'hsl(var(--primary))',
        'primary-foreground': 'hsl(var(--primary-foreground))',
        secondary: 'hsl(var(--secondary))',
        'secondary-foreground': 'hsl(var(--secondary-foreground))',
        accent: 'hsl(var(--accent))',
        'accent-foreground': 'hsl(var(--accent-foreground))',
        muted: 'hsl(var(--muted-foreground))',
        'muted-surface': 'hsl(var(--muted))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        success: '#16A36A',
        warning: '#D97706',
        danger: 'hsl(var(--destructive))',
        'danger-foreground': 'hsl(var(--destructive-foreground))',
        'status-neutral': 'hsl(var(--status-neutral))',
        'status-neutral-foreground': 'hsl(var(--status-neutral-foreground))',
        'status-processing': 'hsl(var(--status-processing))',
        'status-processing-foreground': 'hsl(var(--status-processing-foreground))',
        'status-attention': 'hsl(var(--status-attention))',
        'status-attention-foreground': 'hsl(var(--status-attention-foreground))',
        'status-success': 'hsl(var(--status-success))',
        'status-success-foreground': 'hsl(var(--status-success-foreground))',
        'status-danger': 'hsl(var(--status-danger))',
        'status-danger-foreground': 'hsl(var(--status-danger-foreground))',
      },
      fontFamily: {
        sans: ['Segoe UI Variable', 'Microsoft YaHei UI', 'PingFang SC', 'Segoe UI', 'Arial', 'sans-serif'],
        mono: ['Cascadia Code', 'SFMono-Regular', 'Consolas', 'Liberation Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
